services:
  ml-app:
    image: ml-app:latest
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - hf-cache:/app/model_cache
    environment:
      - HF_HOME=/app/model_cache
    networks:
      - ml-network

volumes:
  hf-cache:

networks:
  ml-network: